project:
  type: website
  output-dir: docs
website:
  title: Getting Started with Git and GitHub in RStudio
  image: images/hot-air-balloon.png
  open-graph:
    title: ""
    description: "Getting Started with Git and GitHub in RStudio."
  twitter-card:
    title: "Getting Started with Git and GitHub in RStudio"
    description: "Getting Started with Git and GitHub in RStudio."
  site-url: https://cbdrh.github.io/git-and-github-in-rstudio
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center:
    - text: © UNSW 2025
  favicon: images/hot-air-balloon.png
  navbar: 
    logo: images/hot-air-balloon.png
    search: true
    left:
    - text: "Home"
      href: index.qmd
      icon: house-fill
    - text: "Slides"
      href: lectures/overview.qmd
      icon: easel3-fill
    - text: "Exercises"
      href: exercises/overview.qmd
      icon: code
      
  sidebar:
      style: "docked"
      background: dark
      contents:
        - text: "Home"
          href: index.qmd
        - text: "Slides"
          href: lectures/overview.qmd 
        - section: "Exercises"
          contents:
            - text: Overview
              href: exercises/overview.qmd
            - text: Exercise 1
              href: exercises/exercise1.qmd
            - text: Exercise 2
              href: exercises/exercise2.qmd
            - text: Exercise 3
              href: exercises/exercise3.qmd
      

format:
  html:
    theme: [darkly, custom.scss]
    toc: true
    toc-depth: 1
    code-copy: true


